channels:
  - defaults
  - spyder-ide
dependencies:
# Main dependencies
- pyqt
- qtpy
- traitlets
- ipython_genutils
- jupyter_core
- pygments
- ipykernel
- pyzmq >=17.1

# For testing
- coveralls
- flaky
- pytest
- pytest-cov
- pytest-qt
